#!/bin/bash

# for elasticsearch update
systemctl daemon-reload

# rename zammad nginx conf if exists - disabled - templated
#[ -f "/etc/nginx/conf.d/zammad.conf" ] && mv /etc/nginx/conf.d/zammad.conf /etc/nginx/conf.d/zammad.disabled

# not needed, done by RPM - needed again to update the plugin
/usr/share/elasticsearch/bin/elasticsearch-plugin -s remove ingest-attachment
yes | /usr/share/elasticsearch/bin/elasticsearch-plugin -s install ingest-attachment

# set vm.max_map_count for elasticsearch - thanks to CptCharlesG

sysctl -w vm.max_map_count=262144

# prepare postgres set postgres template1 to UTF8 for zammad rpm to work if database zammad does not exist

su - postgres -c "psql -lqt | cut -d \| -f 1 | grep -q -w zammad"
if [ $? -eq 1 ]; then
   su - postgres -c "psql -c \"UPDATE pg_database SET encoding = pg_char_to_encoding('UTF8') WHERE datname = 'template1';\""
fi

# reset postgres template1 if database zammad exists to not make problems with other apps

su - postgres -c "psql -lqt | cut -d \| -f 1 | grep -q -w zammad"
if [ $? -eq 0 ]; then
   su - postgres -c "psql -c \"UPDATE pg_database SET encoding = pg_char_to_encoding('SQL_ASCII') WHERE datname = 'template1';\""
fi

# if zammad already installed let it use port 3001 instead of 3000 to not use same port as ntopng

[ -f "/usr/bin/zammad" ] && zammad config:set ZAMMAD_RAILS_PORT=3001

# Setup elasticsearch index - thanks to CptCharlesG

if [[ -f "/usr/bin/zammad" ]]; then
   sudo -u zammad zammad run rails r "Setting.set('es_url', 'http://localhost:9200')"
   sudo -u zammad zammad run rails r "Setting.set('es_index', Socket.gethostname.downcase + '_zammad')"
   sudo -u zammad zammad run rails r "Setting.set('es_attachment_ignore', [ '.png', '.jpg', '.jpeg', '.mpeg', '.mpg', '.mov', '.bin', '.exe', '.box', '.mbox' ] )"
   sudo -u zammad zammad run rails r "Setting.set('es_attachment_max_size_in_mb', 50)"
   sudo -u zammad zammad run rake searchindex:rebuild
fi
