#!/bin/bash

# rename zammad nginx conf if exists
[ -f "/etc/nginx/conf.d/zammad.conf" ] || mv /etc/nginx/conf.d/zammad.conf /etc/nginx/conf.d/zammad.disabled
# not needed, done by RPM
#yes | /usr/share/elasticsearch/bin/elasticsearch-plugin -s install ingest-attachment

# prepare postgres

#su - postgres -c "psql -lqt | cut -d \| -f 1 | grep -q -w zammad"
#if [ $? -eq 1 ]; then

su - postgres -c psql
update pg_database set datallowconn = TRUE where datname = 'template0';
\c template0
update pg_database set datistemplate = FALSE where datname = 'template1';
drop database template1;
create database template1 with template = template0 encoding = 'UTF8';
update pg_database set datistemplate = TRUE where datname = 'template1';
\c template1
update pg_database set datallowconn = FALSE where datname = 'template0';
\q

#fi


